/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    GridBlock: typeof import('./src/components/GridBlock.vue')['default']
    GridContentComponent: typeof import('./src/components/GridContentComponent.vue')['default']
    Knob: typeof import('primevue/knob')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
